# Generated by Django 3.0.7 on 2020-06-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
        migrations.AddField(
            model_name='user',
            name='fullName',
            field=models.CharField(default=6, max_length=128),
            preserve_default=False,
        ),
    ]
