# Generated by Django 3.0.7 on 2020-07-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullName',
            field=models.CharField(max_length=8),
        ),
    ]
